### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by tmampa** [NataliaPoletaeva/Javascript-Capstone-Kanban#21]
In this milestone we have set up the Kanban board:

- [Link to the project](https://github.com/NataliaPoletaeva/Javascript-Capstone-Kanban/projects/2)
- Number of members in the group: 2

**Comment by D4nielJ** [comment]
## Hello @tmampa and @NataliaPoletaeva, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://i.imgur.com/NLzCKYy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
