### ISSUE TITLE
Morning peer-peer code review

### ISSUE THREAD

**Issue by cwaku** [NataliaPoletaeva/Javascript-Capstone-Kanban#28]
That's really great job you have done. Nothing is stopping you from asking for external review

To Highlight: 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error present. ✔️ 
- Great modulization of your codebase ✔️ 
- Good variable naming conventions ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

![](https://media.giphy.com/media/f9RzoxHizH72k15FKS/giphy.gif)

**Comment by kingqabil** [comment]
@kingqabil



👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
👍 The project is perfectly working.

Good job so far!

Cheers and Happy coding!👏👏👏
